export const adminMenu = [
  {
    key: 'dashboard',
    title: 'Dashboard',
    description: 'Overview and live booking metrics',
    icon: 'view-dashboard-outline',
    route: '/admin',
    metricKey: 'pendingBookings',
  },
  {
    key: 'equipment-orders',
    title: 'Equipment Orders',
    description: 'Review rental orders and approvals',
    icon: 'clipboard-list-outline',
    route: '/admin/equipment-orders',
    metricKey: 'equipmentOrders',
  },
  {
    key: 'hotel-rooms',
    title: 'Hotel & Rooms',
    description: 'Manage hotel inventory and room records',
    icon: 'office-building-outline',
    route: '/admin/hotel-rooms',
    metricKey: 'rooms',
  },
  {
    key: 'room-bookings',
    title: 'Room Bookings',
    description: 'Track room reservations and statuses',
    icon: 'bed-outline',
    route: '/admin/room-bookings',
    metricKey: 'roomBookings',
  },
  {
    key: 'storage-equipment',
    title: 'Storage / Equipment',
    description: 'Maintain gear stock and availability',
    icon: 'toolbox-outline',
    route: '/admin/storage-equipment',
    metricKey: 'gearItems',
  },
  {
    key: 'packages',
    title: 'Packages',
    description: 'Maintain tourism packages and offers',
    icon: 'package-variant-closed',
    route: '/admin/packages',
    metricKey: 'packages',
  },
  {
    key: 'transportation',
    title: 'Transportation',
    description: 'Manage safari vehicles and bookings',
    icon: 'jeepney',
    route: '/admin/transportation',
    metricKey: 'vehicles',
  },
  {
    key: 'payments',
    title: 'Payments',
    description: 'Review collected revenue and payment states',
    icon: 'cash-multiple',
    route: '/admin/payments',
    metricKey: 'totalRevenue',
  },
  {
    key: 'restaurant',
    title: 'Restaurant',
    description: 'Manage restaurants, menus, and foods',
    icon: 'silverware-fork-knife',
    route: '/admin/restaurant',
    metricKey: 'restaurantItems',
  },
  {
    key: 'food-orders',
    title: 'Food Orders',
    description: 'Review restaurant orders and customer requests',
    icon: 'food-outline',
    route: '/admin/food-orders',
    metricKey: 'foodOrders',
  },
  {
    key: 'reviews',
    title: 'Reviews',
    description: 'Moderate guest reviews and ratings',
    icon: 'star-box-outline',
    route: '/admin/reviews',
    metricKey: 'reviews',
  },
  {
    key: 'inquiries',
    title: 'Inquiries',
    description: 'Review contact messages and guest requests',
    icon: 'message-alert-outline',
    route: '/admin/inquiries',
    metricKey: 'inquiries',
  },
  {
    key: 'package-vehicles',
    title: 'Package Vehicles',
    description: 'Assign vehicles to package experiences',
    icon: 'car-multiple',
    route: '/admin/package-vehicles',
    metricKey: 'packageVehicles',
  },
  {
    key: 'package-bookings',
    title: 'Package Bookings',
    description: 'Track package reservations and demand',
    icon: 'ticket-confirmation-outline',
    route: '/admin/package-bookings',
    metricKey: 'packageBookings',
  },
  {
    key: 'users',
    title: 'Users',
    description: 'Monitor users and account access',
    icon: 'account-group-outline',
    route: '/admin/users',
    metricKey: 'users',
  },
  {
    key: 'logout',
    title: 'Logout',
    description: 'Sign out from the admin dashboard',
    icon: 'logout',
    route: null,
    metricKey: null,
    action: 'logout',
  },
];

export function getAdminMenuItem(key) {
  return adminMenu.find((item) => item.key === key) || null;
}
