export const services = [
  {
    id: 'hotels',
    title: 'Hotels',
    description: 'Explore resort properties, locations, and hotel experiences.',
    icon: 'office-building-outline',
    route: '/hotels',
    accent: 'info',
  },
  {
    id: 'rooms',
    title: 'Rooms',
    description: 'Browse premium accommodation and room availability.',
    icon: 'bed-queen-outline',
    route: '/rooms',
    accent: 'primary',
  },
  {
    id: 'packages',
    title: 'Packages',
    description: 'Explore curated resort and safari travel packages.',
    icon: 'map-search-outline',
    route: '/packages',
    accent: 'accent',
  },
  {
    id: 'safari-vehicles',
    title: 'Safari Vehicles',
    description: 'View jeeps, transport options, and safari rides.',
    icon: 'jeepney',
    route: '/vehicles',
    accent: 'primary',
  },
  {
    id: 'restaurants',
    title: 'Restaurants',
    description: 'Discover dining options, menus, and food experiences.',
    icon: 'silverware-fork-knife',
    route: '/restaurants',
    accent: 'accent',
  },
  {
    id: 'gear-rental-storage',
    title: 'Gear Rental / Storage',
    description: 'Check gear availability, rentals, and storage services.',
    icon: 'bag-personal-outline',
    route: '/gear-rental',
    accent: 'warning',
  },
  {
    id: 'my-bookings',
    title: 'My Bookings',
    description: 'Track room, package, and safari reservations in one place.',
    icon: 'calendar-check-outline',
    route: '/my-bookings',
    accent: 'warning',
  },
  {
    id: 'reviews',
    title: 'Reviews',
    description: 'Read and share guest feedback across services.',
    icon: 'star-outline',
    route: '/reviews',
    accent: 'info',
  },
  {
    id: 'contact-us',
    title: 'Contact Us',
    description: 'Reach the team for support, inquiries, and assistance.',
    icon: 'message-text-outline',
    route: '/contact-us',
    accent: 'info',
  },
];
